apiVersion: apps/v1
kind: Deployment
metadata:
  name: pedidos-ms
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pedidos-ms
  template:
    metadata:
      labels:
        app: pedidos-ms
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: "/actuator/prometheus"
        prometheus.io/port: "8082"
    spec:
      containers:
        - name: pedidos-ms
          image: danttee/pedidos-ms:latest
          ports:
            - containerPort: 8082
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8082
            initialDelaySeconds: 20
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8082
            initialDelaySeconds: 30
            periodSeconds: 15
---
apiVersion: v1
kind: Service
metadata:
  name: pedidos-ms
spec:
  selector:
    app: pedidos-ms
  ports:
    - protocol: TCP
      port: 8082
      targetPort: 8082
  type: ClusterIP